# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 dial481
"""Parser for AncestryDNA raw genotype export files.

Format reference (from real sample files and snps package):

    #AncestryDNA raw data download
    #This file was generated by AncestryDNA ...
    #Data was collected using AncestryDNA array version: V2.0
    #
    rsid    chromosome    position    allele1    allele2
    rs4477212    1    82154    A    C
    rs9001001    1    100000    0    0

Specifics:
    - Comment lines start with ``#``.
    - Tab-delimited, 5 columns of data (alleles in separate columns).
    - Detection key: ``#AncestryDNA`` in the first comment line.
    - Chromosome codes: 23 = X, 24 = Y, 25 = PAR (pseudo-autosomal,
      mapped to X), 26 = MT.
    - No-calls represented as ``0`` for each allele.
    - Build 37 (GRCh37).
    - V1 chip (pre-May 2016, ~682K SNPs) and V2 chip (May 2016+,
      ~664K SNPs) share the same column layout.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, ClassVar

from allelix.models import DEFAULT_BUILD, NO_CALL_MARKER, Variant
from allelix.parsers.base import GenotypeMetadata, GenotypeParser

if TYPE_CHECKING:
    from collections.abc import Iterator
    from pathlib import Path

logger = logging.getLogger(__name__)

SIGNATURE = "#AncestryDNA"
EXPECTED_HEADER = "rsid\tchromosome\tposition\tallele1\tallele2"
EXPECTED_COLUMNS = 5
SNIFF_LINE_LIMIT = 50

_CHROM_MAP: dict[str, str] = {
    "23": "X",
    "24": "Y",
    "25": "X",
    "26": "MT",
}


class AncestryDNAParser(GenotypeParser):
    """Parser for AncestryDNA consumer DNA genotype files."""

    name: ClassVar[str] = "ancestrydna"
    display_name: ClassVar[str] = "AncestryDNA"
    file_extensions: ClassVar[list[str]] = [".txt"]
    url: ClassVar[str] = "https://www.ancestry.com/dna"

    def can_parse(self, file_path: Path) -> bool:
        """Recognize the file by its ``#AncestryDNA`` signature on the first line."""
        try:
            with file_path.open("r", encoding="utf-8") as fh:
                first_line = fh.readline()
                return first_line.startswith(SIGNATURE)
        except (OSError, UnicodeDecodeError):
            return False

    def parse(self, file_path: Path) -> Iterator[Variant]:
        """Stream Variant objects, skipping comments and malformed lines."""
        with file_path.open("r", encoding="utf-8") as fh:
            header_seen = False
            for lineno, raw in enumerate(fh, start=1):
                line = raw.rstrip("\r\n")
                if not line or line.startswith("#"):
                    continue
                if not header_seen:
                    if line == EXPECTED_HEADER:
                        header_seen = True
                        continue
                    logger.warning(
                        "Line %d: expected header %r, got %r — skipping",
                        lineno,
                        EXPECTED_HEADER,
                        line,
                    )
                    continue

                parts = line.split("\t")
                if len(parts) != EXPECTED_COLUMNS:
                    logger.warning(
                        "Line %d: expected %d columns, got %d — skipping",
                        lineno,
                        EXPECTED_COLUMNS,
                        len(parts),
                    )
                    continue

                rsid, chrom_raw, pos_str, allele1, allele2 = parts
                try:
                    position = int(pos_str)
                except ValueError:
                    logger.warning("Line %d: invalid position %r — skipping", lineno, pos_str)
                    continue

                chrom = _CHROM_MAP.get(chrom_raw, chrom_raw)

                if allele1 == "0":
                    allele1 = NO_CALL_MARKER
                if allele2 == "0":
                    allele2 = NO_CALL_MARKER

                yield Variant(
                    rsid=rsid,
                    chromosome=chrom,
                    position=position,
                    allele1=allele1,
                    allele2=allele2,
                    build=DEFAULT_BUILD,
                )

    def get_metadata(self, file_path: Path) -> GenotypeMetadata:
        """Extract metadata from header comments. AncestryDNA has no sample ID field."""
        return GenotypeMetadata(
            format=self.name,
            sample_id="",
            build=DEFAULT_BUILD,
        )
