# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 dial481
"""Parser for MyHappyGenes (Tempus) genotype export files.

Format reference (from sample  file):

    # MyHappyGenes [TEMPUS]
    # This file was generated by MyHappyGenes, Inc.
    # ... (additional comment lines)
    # Sample ID    MHG000001
    SNP Name    Chr    Position    Allele1 - Forward    Allele2 - Forward
    rs9651229    1    632287    C    C
    rs9701872    1    632828    T    T

Specifics:
    - Comment lines start with `#`.
    - Tab-delimited, 5 columns of data.
    - Header claims build 37.1, but real-world exports we've verified
      contain GRCh38 positions. The analyze pipeline runs auto-
      detection (ADR-0021) and overrides the parser-reported build
      based on position data. The build value returned here reflects
      the literal header claim; downstream code should not assume it.
      Forward strand with respect to the reference.
    - No-calls represented as `-`.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, ClassVar

from allelix.models import DEFAULT_BUILD, Variant
from allelix.parsers.base import GenotypeMetadata, GenotypeParser

if TYPE_CHECKING:
    from collections.abc import Iterator
    from pathlib import Path

logger = logging.getLogger(__name__)

SIGNATURE = "# MyHappyGenes"
SAMPLE_ID_PREFIX = "# Sample ID"
EXPECTED_HEADER = "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward"
EXPECTED_COLUMNS = 5
SNIFF_LINE_LIMIT = 50


class MyHappyGenesParser(GenotypeParser):
    """Parser for MyHappyGenes/Tempus consumer DNA genotype files."""

    name: ClassVar[str] = "myhappygenes"
    display_name: ClassVar[str] = "MyHappyGenes (Tempus)"
    file_extensions: ClassVar[list[str]] = [".txt"]
    url: ClassVar[str] = "https://myhappygenes.com"

    def can_parse(self, file_path: Path) -> bool:
        """Recognize the file by its `# MyHappyGenes` signature line."""
        try:
            with file_path.open("r", encoding="utf-8") as fh:
                for _ in range(SNIFF_LINE_LIMIT):
                    line = fh.readline()
                    if not line:
                        return False
                    if SIGNATURE in line:
                        return True
        except (OSError, UnicodeDecodeError):
            return False
        return False

    def parse(self, file_path: Path) -> Iterator[Variant]:
        """Stream Variant objects, skipping comments and malformed lines."""
        with file_path.open("r", encoding="utf-8") as fh:
            header_seen = False
            for lineno, raw in enumerate(fh, start=1):
                line = raw.rstrip("\r\n")
                if not line or line.startswith("#"):
                    continue
                if not header_seen:
                    if line == EXPECTED_HEADER:
                        header_seen = True
                        continue
                    logger.warning(
                        "Line %d: expected header %r, got %r — skipping",
                        lineno,
                        EXPECTED_HEADER,
                        line,
                    )
                    continue

                parts = line.split("\t")
                if len(parts) != EXPECTED_COLUMNS:
                    logger.warning(
                        "Line %d: expected %d columns, got %d — skipping",
                        lineno,
                        EXPECTED_COLUMNS,
                        len(parts),
                    )
                    continue

                rsid, chrom, pos_str, allele1, allele2 = parts
                try:
                    position = int(pos_str)
                except ValueError:
                    logger.warning("Line %d: invalid position %r — skipping", lineno, pos_str)
                    continue

                yield Variant(
                    rsid=rsid,
                    chromosome=chrom,
                    position=position,
                    allele1=allele1,
                    allele2=allele2,
                    build=DEFAULT_BUILD,
                )

    def get_metadata(self, file_path: Path) -> GenotypeMetadata:
        """Extract sample ID from the file header. Cheap — no full parse."""
        sample_id = ""
        with file_path.open("r", encoding="utf-8") as fh:
            for raw in fh:
                line = raw.rstrip("\r\n")
                if not line:
                    continue
                if line.startswith(SAMPLE_ID_PREFIX):
                    parts = line.split("\t", 1)
                    if len(parts) == 2:
                        sample_id = parts[1].strip()
                    break
                if not line.startswith("#"):
                    break
        return GenotypeMetadata(
            format=self.name,
            sample_id=sample_id,
            build=DEFAULT_BUILD,
        )
