# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 dial481
"""Parser for 23andMe raw genotype export files.

Format reference (from real sample files and snps package):

    # This data file generated by 23andMe at: Mon Jun 01 00:00:00 2020
    #
    # This file contains raw genotype data ...
    #
    # rsid  chromosome  position  genotype
    rs4477212	1	82154	AA
    rs3094315	1	752566	AG
    i3000043	5	33951693	CT
    rs9001001	1	100000	--

Specifics:
    - Comment lines start with `#`.
    - Tab-delimited, 4 columns of data.
    - Genotype is concatenated in one column (e.g., "AG" not "A<tab>G").
    - Haploid calls on X/Y/MT appear as single characters (e.g., "A").
    - No-calls represented as `--`.
    - Contains I-prefixed internal probe IDs (i3000043, i5006212)
      alongside rs-numbers. These are passed through as-is.
    - Build 37 (older) or Build 38 (newer); check header comments.
    - Detection key: "23andMe" in early comment lines.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, ClassVar

from allelix.models import DEFAULT_BUILD, NO_CALL_MARKER, Variant
from allelix.parsers.base import GenotypeMetadata, GenotypeParser

if TYPE_CHECKING:
    from collections.abc import Iterator
    from pathlib import Path

logger = logging.getLogger(__name__)

SIGNATURE = "23andMe"
SNIFF_LINE_LIMIT = 50
EXPECTED_COLUMNS = 4


class TwentyThreeAndMeParser(GenotypeParser):
    """Parser for 23andMe consumer DNA genotype files."""

    name: ClassVar[str] = "23andme"
    display_name: ClassVar[str] = "23andMe"
    file_extensions: ClassVar[list[str]] = [".txt"]
    url: ClassVar[str] = "https://www.23andme.com"

    def can_parse(self, file_path: Path) -> bool:
        """Recognize the file by its `23andMe` signature in early comment lines."""
        try:
            with file_path.open("r", encoding="utf-8") as fh:
                for _ in range(SNIFF_LINE_LIMIT):
                    line = fh.readline()
                    if not line:
                        return False
                    if not line.startswith("#"):
                        return False
                    if SIGNATURE in line:
                        return True
        except (OSError, UnicodeDecodeError):
            return False
        return False

    def parse(self, file_path: Path) -> Iterator[Variant]:
        """Stream Variant objects, skipping comments and malformed lines."""
        with file_path.open("r", encoding="utf-8") as fh:
            for lineno, raw in enumerate(fh, start=1):
                line = raw.rstrip("\r\n")
                if not line or line.startswith("#"):
                    continue

                parts = line.split("\t")
                if len(parts) != EXPECTED_COLUMNS:
                    logger.warning(
                        "Line %d: expected %d columns, got %d — skipping",
                        lineno,
                        EXPECTED_COLUMNS,
                        len(parts),
                    )
                    continue

                rsid, chrom, pos_str, genotype = parts
                try:
                    position = int(pos_str)
                except ValueError:
                    logger.warning("Line %d: invalid position %r — skipping", lineno, pos_str)
                    continue

                allele1, allele2 = _split_genotype(genotype)

                yield Variant(
                    rsid=rsid,
                    chromosome=chrom,
                    position=position,
                    allele1=allele1,
                    allele2=allele2,
                    build=DEFAULT_BUILD,
                )

    def get_metadata(self, file_path: Path) -> GenotypeMetadata:
        """Extract build from header comments. 23andMe files have no sample ID field."""
        build = DEFAULT_BUILD
        with file_path.open("r", encoding="utf-8") as fh:
            for raw in fh:
                line = raw.rstrip("\r\n")
                if not line.startswith("#"):
                    break
                lowered = line.lower()
                if "build 36" in lowered or "hg18" in lowered:
                    build = "GRCh36"
                elif "build 37" in lowered or "grch37" in lowered:
                    build = "GRCh37"
                elif "build 38" in lowered or "grch38" in lowered:
                    build = "GRCh38"
        return GenotypeMetadata(
            format=self.name,
            sample_id="",
            build=build,
        )


def _split_genotype(genotype: str) -> tuple[str, str]:
    """Split a concatenated genotype field into two alleles.

    "AG" → ("A", "G"), "--" → ("-", "-"), "A" → ("A", "A") (haploid).
    """
    if genotype == "--":
        return NO_CALL_MARKER, NO_CALL_MARKER
    if len(genotype) == 2:
        return genotype[0], genotype[1]
    if len(genotype) == 1:
        return genotype, genotype
    logger.warning("Unexpected genotype format %r — treating as no-call", genotype)
    return NO_CALL_MARKER, NO_CALL_MARKER
