# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 dial481
"""Tests for the AncestryDNA parser."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from allelix.parsers.ancestrydna import AncestryDNAParser

if TYPE_CHECKING:
    from pathlib import Path


@pytest.fixture
def parser() -> AncestryDNAParser:
    return AncestryDNAParser()


def _write(tmp_path: Path, contents: str, name: str = "f.txt") -> Path:
    f = tmp_path / name
    f.write_text(contents, encoding="utf-8")
    return f


class TestParserAttributes:
    def test_required_metadata(self, parser: AncestryDNAParser) -> None:
        assert parser.name == "ancestrydna"
        assert parser.display_name == "AncestryDNA"
        assert ".txt" in parser.file_extensions
        assert parser.url


class TestCanParse:
    def test_recognizes_real_fixture(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        assert parser.can_parse(mock_ancestrydna_path) is True

    def test_rejects_23andme_file(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# This data file generated by 23andMe\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1\t1\t100\tAG\n",
        )
        assert parser.can_parse(f) is False

    def test_rejects_myhappygenes_file(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n",
        )
        assert parser.can_parse(f) is False

    def test_rejects_empty_file(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(tmp_path, "")
        assert parser.can_parse(f) is False

    def test_rejects_missing_file(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        assert parser.can_parse(tmp_path / "does_not_exist.txt") is False

    def test_rejects_binary_file(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = tmp_path / "binary.txt"
        f.write_bytes(b"\x00\x01\x02\xff\xfe")
        assert parser.can_parse(f) is False


class TestParse:
    def test_yields_variants_from_fixture(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        assert len(variants) == 12

    def test_known_mthfr_variant(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        mthfr = next(v for v in variants if v.rsid == "rs1801133")
        assert mthfr.chromosome == "1"
        assert mthfr.position == 11856378
        assert mthfr.allele1 == "A"
        assert mthfr.allele2 == "G"
        assert mthfr.is_heterozygous

    def test_homozygous_variant(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        v = next(v for v in variants if v.rsid == "rs1065852")
        assert v.allele1 == "C"
        assert v.allele2 == "C"
        assert not v.is_heterozygous

    def test_no_calls_mapped_from_zero(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        no_call = next(v for v in variants if v.rsid == "rs9001001")
        assert no_call.is_no_call
        assert no_call.allele1 == "-"
        assert no_call.allele2 == "-"

    def test_chromosome_23_maps_to_x(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        x = next(v for v in variants if v.rsid == "rs9001003")
        assert x.chromosome == "X"

    def test_chromosome_24_maps_to_y(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        y = next(v for v in variants if v.rsid == "rs9001004")
        assert y.chromosome == "Y"

    def test_chromosome_25_par_maps_to_x(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        par = next(v for v in variants if v.rsid == "rs9001005")
        assert par.chromosome == "X"

    def test_chromosome_26_maps_to_mt(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        variants = list(parser.parse(mock_ancestrydna_path))
        mt = next(v for v in variants if v.rsid == "rs9001002")
        assert mt.chromosome == "MT"

    def test_skips_comment_lines(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "#AncestryDNA raw data download\n"
            "#comment\n"
            "#\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs1\t1\t100\tA\tG\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].rsid == "rs1"

    def test_skips_blank_lines(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "#AncestryDNA\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "\n"
            "rs1\t1\t100\tA\tG\n"
            "\n"
            "rs2\t2\t200\tT\tC\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 2

    def test_skips_malformed_column_count(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "#AncestryDNA\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs1\t1\t100\tA\tG\n"
            "this is malformed\n"
            "rs2\t2\t200\tC\tT\n",
        )
        variants = list(parser.parse(f))
        assert [v.rsid for v in variants] == ["rs1", "rs2"]

    def test_skips_invalid_position(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "#AncestryDNA\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs1\t1\tNOT_A_NUMBER\tA\tG\n"
            "rs2\t2\t200\tC\tT\n",
        )
        variants = list(parser.parse(f))
        assert [v.rsid for v in variants] == ["rs2"]

    def test_handles_crlf_line_endings(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "#AncestryDNA\r\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\r\n"
            "rs1\t1\t100\tA\tG\r\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].allele1 == "A"
        assert variants[0].allele2 == "G"

    def test_streaming_returns_iterator(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        result = parser.parse(mock_ancestrydna_path)
        assert iter(result) is result or hasattr(result, "__next__")

    def test_v2_chip_format(self, parser: AncestryDNAParser, tmp_path: Path) -> None:
        """V2 chip has an array version comment but same column layout."""
        f = _write(
            tmp_path,
            "#AncestryDNA raw data download\n"
            "#Data was collected using AncestryDNA array version: V2.0\n"
            "#\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs1\t1\t100\tA\tG\n",
        )
        assert parser.can_parse(f)
        variants = list(parser.parse(f))
        assert len(variants) == 1

    def test_warns_on_garbage_before_header(
        self, parser: AncestryDNAParser, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        f = _write(
            tmp_path,
            "#AncestryDNA\n"
            "garbage line\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs1\t1\t100\tA\tG\n",
        )
        with caplog.at_level("WARNING", logger="allelix.parsers.ancestrydna"):
            variants = list(parser.parse(f))
        assert len(variants) == 1
        assert any("expected header" in record.message for record in caplog.records)


class TestMetadata:
    def test_metadata_format_and_build(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        meta = parser.get_metadata(mock_ancestrydna_path)
        assert meta["format"] == "ancestrydna"
        assert meta["build"] == "GRCh37"
        assert meta["sample_id"] == ""

    def test_metadata_has_no_snp_count_field(
        self, parser: AncestryDNAParser, mock_ancestrydna_path: Path
    ) -> None:
        meta = parser.get_metadata(mock_ancestrydna_path)
        assert "snp_count" not in meta


class TestEdgeCases:
    def test_header_only_file_yields_zero_variants(
        self, parser: AncestryDNAParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "#AncestryDNA raw data download\n#\nrsid\tchromosome\tposition\tallele1\tallele2\n",
        )
        assert parser.can_parse(f) is True
        assert list(parser.parse(f)) == []

    def test_single_zero_allele_is_partial_no_call(
        self, parser: AncestryDNAParser, tmp_path: Path
    ) -> None:
        """One allele 0 and one allele A → partial no-call."""
        f = _write(
            tmp_path,
            "#AncestryDNA\nrsid\tchromosome\tposition\tallele1\tallele2\nrs1\t1\t100\t0\tA\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].allele1 == "-"
        assert variants[0].allele2 == "A"
        assert variants[0].is_no_call


class TestAutoDetection:
    def test_registry_detects_ancestrydna(self, mock_ancestrydna_path: Path) -> None:
        from allelix.parsers import detect_parser

        parser = detect_parser(mock_ancestrydna_path)
        assert parser.name == "ancestrydna"

    def test_registry_lookup_by_name(self) -> None:
        from allelix.parsers import get_parser_by_name

        parser = get_parser_by_name("ancestrydna")
        assert isinstance(parser, AncestryDNAParser)

    def test_mhg_not_confused_with_ancestrydna(self, mock_mhg_path: Path) -> None:
        from allelix.parsers import detect_parser

        parser = detect_parser(mock_mhg_path)
        assert parser.name == "myhappygenes"

    def test_23andme_not_confused_with_ancestrydna(self, mock_23andme_path: Path) -> None:
        from allelix.parsers import detect_parser

        parser = detect_parser(mock_23andme_path)
        assert parser.name == "23andme"
