# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 dial481
"""Tests for the MyHappyGenes parser."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from allelix.parsers.myhappygenes import MyHappyGenesParser

if TYPE_CHECKING:
    from pathlib import Path


@pytest.fixture
def parser() -> MyHappyGenesParser:
    return MyHappyGenesParser()


def _write(tmp_path: Path, contents: str, name: str = "f.txt") -> Path:
    f = tmp_path / name
    f.write_text(contents, encoding="utf-8")
    return f


class TestParserAttributes:
    def test_required_metadata(self, parser):
        assert parser.name == "myhappygenes"
        assert parser.display_name
        assert ".txt" in parser.file_extensions
        assert parser.url


class TestCanParse:
    def test_recognizes_real_fixture(self, parser, mock_mhg_path):
        assert parser.can_parse(mock_mhg_path) is True

    def test_rejects_23andme_style_file(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# This data file generated by 23andMe at: 2020-01-01\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1\t1\t100\tAG\n",
        )
        assert parser.can_parse(f) is False

    def test_rejects_empty_file(self, parser, tmp_path):
        f = _write(tmp_path, "")
        assert parser.can_parse(f) is False

    def test_rejects_missing_file(self, parser, tmp_path):
        assert parser.can_parse(tmp_path / "does_not_exist.txt") is False

    def test_rejects_binary_file(self, parser, tmp_path):
        f = tmp_path / "binary.txt"
        f.write_bytes(b"\x00\x01\x02\xff\xfe")
        assert parser.can_parse(f) is False

    def test_rejects_when_signature_beyond_sniff_limit(self, parser, tmp_path):
        """The signature must appear within SNIFF_LINE_LIMIT lines or it doesn't count."""
        from allelix.parsers.myhappygenes import SNIFF_LINE_LIMIT

        f = tmp_path / "late_signature.txt"
        padding = "# padding line\n" * (SNIFF_LINE_LIMIT + 5)
        f.write_text(padding + "# MyHappyGenes [TEMPUS]\n", encoding="utf-8")
        assert parser.can_parse(f) is False


class TestParse:
    def test_yields_variants_from_fixture(self, parser, mock_mhg_path):
        variants = list(parser.parse(mock_mhg_path))
        assert len(variants) > 100

    def test_known_mthfr_variant(self, parser, mock_mhg_path):
        variants = list(parser.parse(mock_mhg_path))
        mthfr = next(v for v in variants if v.rsid == "rs1801133")
        assert mthfr.chromosome == "1"
        assert mthfr.position == 11796321
        assert mthfr.allele1 == "G"
        assert mthfr.allele2 == "A"
        assert mthfr.is_heterozygous
        assert mthfr.build == "GRCh37"

    def test_known_homozygous_variant(self, parser, mock_mhg_path):
        variants = list(parser.parse(mock_mhg_path))
        comt = next(v for v in variants if v.rsid == "rs4680")
        assert comt.allele1 == "A"
        assert comt.allele2 == "A"
        assert not comt.is_heterozygous
        assert not comt.is_no_call

    def test_no_calls_preserved(self, parser, mock_mhg_path):
        variants = list(parser.parse(mock_mhg_path))
        no_calls = [v for v in variants if v.is_no_call]
        assert len(no_calls) >= 2

    def test_cftr_indel_position_is_no_call(self, parser, mock_mhg_path):
        """ADR-0015: arrays cannot call indels. rs113993960 (CFTR ΔF508) must
        appear as a no-call ('-/-') in the mock fixture, NOT as a multi-base
        genotype. Earlier versions of the generator wrote 'CTT/C' here, which
        violated the MHG format and hid the ClinVar indel-anchor bug.
        """
        variants = list(parser.parse(mock_mhg_path))
        cftr = next(v for v in variants if v.rsid == "rs113993960")
        assert cftr.is_no_call
        assert cftr.allele1 == "-"
        assert cftr.allele2 == "-"

    def test_skips_comment_lines(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "# comment 1\n"
            "# Sample ID\tMHG_X\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\t100\tA\tG\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].rsid == "rs1"

    def test_skips_blank_lines(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "\n"
            "rs1\t1\t100\tA\tG\n"
            "\n"
            "rs2\t2\t200\tT\tC\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 2

    def test_skips_malformed_column_count(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\t100\tA\tG\n"
            "this is malformed\n"
            "rs2\t2\t200\tC\tT\n",
        )
        variants = list(parser.parse(f))
        assert [v.rsid for v in variants] == ["rs1", "rs2"]

    def test_warns_on_garbage_before_header(self, parser, tmp_path, caplog):
        """A non-comment, non-blank line before the header logs a warning and continues."""
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "garbage line that isn't the header\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\t100\tA\tG\n",
        )
        with caplog.at_level("WARNING", logger="allelix.parsers.myhappygenes"):
            variants = list(parser.parse(f))
        assert len(variants) == 1
        assert any("expected header" in record.message for record in caplog.records)

    def test_skips_invalid_position(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\tNOT_A_NUMBER\tA\tG\n"
            "rs2\t2\t200\tC\tT\n",
        )
        variants = list(parser.parse(f))
        assert [v.rsid for v in variants] == ["rs2"]

    def test_handles_chromosomes_x_y_mt(self, parser, mock_mhg_path):
        variants = list(parser.parse(mock_mhg_path))
        chroms = {v.chromosome for v in variants}
        assert "X" in chroms
        assert "Y" in chroms
        assert "MT" in chroms

    def test_handles_crlf_line_endings(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\r\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\r\n"
            "rs1\t1\t100\tA\tG\r\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].allele2 == "G"

    def test_streaming_returns_iterator(self, parser, mock_mhg_path):
        result = parser.parse(mock_mhg_path)
        assert iter(result) is result or hasattr(result, "__next__")


class TestMetadata:
    def test_extracts_sample_id(self, parser, mock_mhg_path):
        meta = parser.get_metadata(mock_mhg_path)
        assert meta["sample_id"] == "MHG000001"
        assert meta["build"] == "GRCh37"
        assert meta["format"] == "myhappygenes"

    def test_metadata_has_no_snp_count_field(self, parser, mock_mhg_path):
        meta = parser.get_metadata(mock_mhg_path)
        assert "snp_count" not in meta

    def test_metadata_skips_blank_lines_in_header(self, parser, tmp_path):
        """Blank lines inside the header section don't terminate the scan."""
        f = _write(
            tmp_path,
            "\n"  # blank line first
            "# MyHappyGenes [TEMPUS]\n"
            "\n"  # blank line in middle of comments
            "# Sample ID\tMHG_BLANKED\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\t100\tA\tG\n",
        )
        meta = parser.get_metadata(f)
        assert meta["sample_id"] == "MHG_BLANKED"

    def test_empty_sample_id_when_missing(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\t100\tA\tG\n",
        )
        meta = parser.get_metadata(f)
        assert meta["sample_id"] == ""


class TestEdgeCases:
    def test_header_only_file_yields_zero_variants(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "# Sample ID\tMHG_EMPTY\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n",
        )
        assert parser.can_parse(f) is True
        assert list(parser.parse(f)) == []
        meta = parser.get_metadata(f)
        assert meta["sample_id"] == "MHG_EMPTY"

    def test_metadata_count_matches_parse_count_with_malformed_lines(self, parser, tmp_path):
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "# Sample ID\tMHG_X\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\t100\tA\tG\n"
            "this_is_garbage\n"
            "rs2\t2\tNOT_A_NUMBER\tA\tG\n"
            "rs3\t3\t300\tC\tT\n",
        )
        valid_count = sum(1 for _ in parser.parse(f))
        assert valid_count == 2
