# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 dial481
"""Tests for the 23andMe parser."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from allelix.parsers.twentythreeandme import TwentyThreeAndMeParser

if TYPE_CHECKING:
    from pathlib import Path


@pytest.fixture
def parser() -> TwentyThreeAndMeParser:
    return TwentyThreeAndMeParser()


def _write(tmp_path: Path, contents: str, name: str = "f.txt") -> Path:
    f = tmp_path / name
    f.write_text(contents, encoding="utf-8")
    return f


class TestParserAttributes:
    def test_required_metadata(self, parser: TwentyThreeAndMeParser) -> None:
        assert parser.name == "23andme"
        assert parser.display_name == "23andMe"
        assert ".txt" in parser.file_extensions
        assert parser.url


class TestCanParse:
    def test_recognizes_real_fixture(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        assert parser.can_parse(mock_23andme_path) is True

    def test_rejects_myhappygenes_file(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "# MyHappyGenes [TEMPUS]\n"
            "SNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
            "rs1\t1\t100\tA\tG\n",
        )
        assert parser.can_parse(f) is False

    def test_rejects_empty_file(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(tmp_path, "")
        assert parser.can_parse(f) is False

    def test_rejects_missing_file(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        assert parser.can_parse(tmp_path / "does_not_exist.txt") is False

    def test_rejects_binary_file(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = tmp_path / "binary.txt"
        f.write_bytes(b"\x00\x01\x02\xff\xfe")
        assert parser.can_parse(f) is False

    def test_rejects_when_signature_beyond_sniff_limit(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        from allelix.parsers.twentythreeandme import SNIFF_LINE_LIMIT

        f = tmp_path / "late_signature.txt"
        padding = "# padding line\n" * (SNIFF_LINE_LIMIT + 5)
        f.write_text(
            padding + "# This data file generated by 23andMe at: ...\n",
            encoding="utf-8",
        )
        assert parser.can_parse(f) is False

    def test_rejects_non_comment_before_signature(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "not a comment\n# This data file generated by 23andMe\n",
        )
        assert parser.can_parse(f) is False

    def test_rejects_bare_23andme_mention(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        """A file that mentions '23andMe' without the canonical prefix is rejected."""
        f = _write(
            tmp_path,
            "# transcoded from 23andMe using third-party tool\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1\t1\t100\tAG\n",
        )
        assert parser.can_parse(f) is False

    def test_recognizes_user_prepended_comments(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        """Canonical header after user-prepended comments is still detected."""
        f = _write(
            tmp_path,
            "# results of my Tipsy Test (courtesy of BGI)\n"
            "# uploaded to opensnp on 2017-03-15\n"
            "# This data file generated by 23andMe at: Tue Mar 14 12:00:00 2017\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1\t1\t100\tAG\n",
        )
        assert parser.can_parse(f) is True


class TestParse:
    def test_yields_variants_from_fixture(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        variants = list(parser.parse(mock_23andme_path))
        assert len(variants) == 12

    def test_known_mthfr_variant(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        variants = list(parser.parse(mock_23andme_path))
        mthfr = next(v for v in variants if v.rsid == "rs1801133")
        assert mthfr.chromosome == "1"
        assert mthfr.position == 11856378
        assert mthfr.allele1 == "A"
        assert mthfr.allele2 == "G"
        assert mthfr.is_heterozygous

    def test_concatenated_genotype_split(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        variants = list(parser.parse(mock_23andme_path))
        comt = next(v for v in variants if v.rsid == "rs4680")
        assert comt.allele1 == "A"
        assert comt.allele2 == "G"
        assert comt.is_heterozygous

    def test_homozygous_variant(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        variants = list(parser.parse(mock_23andme_path))
        v = next(v for v in variants if v.rsid == "rs1065852")
        assert v.allele1 == "C"
        assert v.allele2 == "C"
        assert not v.is_heterozygous

    def test_no_calls_preserved(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        variants = list(parser.parse(mock_23andme_path))
        no_call = next(v for v in variants if v.rsid == "rs9001001")
        assert no_call.is_no_call
        assert no_call.allele1 == "-"
        assert no_call.allele2 == "-"

    def test_i_probe_ids_passed_through(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        variants = list(parser.parse(mock_23andme_path))
        iprobe = next(v for v in variants if v.rsid == "i3000043")
        assert iprobe.chromosome == "5"
        assert iprobe.allele1 == "C"
        assert iprobe.allele2 == "T"

    def test_mt_chromosome(self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path) -> None:
        variants = list(parser.parse(mock_23andme_path))
        mt = next(v for v in variants if v.rsid == "rs9001002")
        assert mt.chromosome == "MT"

    def test_x_chromosome(self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path) -> None:
        variants = list(parser.parse(mock_23andme_path))
        x = next(v for v in variants if v.rsid == "rs9001003")
        assert x.chromosome == "X"
        assert x.allele1 == "A"
        assert x.allele2 == "G"

    def test_haploid_y_chromosome(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        variants = list(parser.parse(mock_23andme_path))
        y = next(v for v in variants if v.rsid == "rs9001004")
        assert y.chromosome == "Y"
        assert y.allele1 == "A"
        assert y.allele2 == "A"

    def test_skips_comment_lines(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# This data file generated by 23andMe\n"
            "# comment\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1\t1\t100\tAG\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].rsid == "rs1"

    def test_skips_blank_lines(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# 23andMe\n\nrs1\t1\t100\tAG\n\nrs2\t2\t200\tTC\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 2

    def test_skips_malformed_column_count(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "# 23andMe\nrs1\t1\t100\tAG\nthis is malformed\nrs2\t2\t200\tCT\n",
        )
        variants = list(parser.parse(f))
        assert [v.rsid for v in variants] == ["rs1", "rs2"]

    def test_skips_invalid_position(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# 23andMe\nrs1\t1\tNOT_A_NUMBER\tAG\nrs2\t2\t200\tCT\n",
        )
        variants = list(parser.parse(f))
        assert [v.rsid for v in variants] == ["rs2"]

    def test_handles_crlf_line_endings(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "# 23andMe\r\nrs1\t1\t100\tAG\r\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].allele1 == "A"
        assert variants[0].allele2 == "G"

    def test_streaming_returns_iterator(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        result = parser.parse(mock_23andme_path)
        assert iter(result) is result or hasattr(result, "__next__")


class TestMetadata:
    def test_extracts_build_37(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        meta = parser.get_metadata(mock_23andme_path)
        assert meta["build"] == "GRCh37"
        assert meta["format"] == "23andme"
        assert meta["sample_id"] == ""

    def test_detects_build_38(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# This data file generated by 23andMe\n"
            "# We are using reference human assembly build 38\n"
            "rs1\t1\t100\tAG\n",
        )
        meta = parser.get_metadata(f)
        assert meta["build"] == "GRCh38"

    def test_detects_build_36(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# This data file generated by 23andMe\n"
            "# We are using reference human assembly build 36\n"
            "rs1\t1\t100\tAG\n",
        )
        meta = parser.get_metadata(f)
        assert meta["build"] == "GRCh36"

    def test_detects_hg18_label(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# 23andMe file using hg18 coordinates\nrs1\t1\t100\tAG\n",
        )
        meta = parser.get_metadata(f)
        assert meta["build"] == "GRCh36"

    def test_detects_grch38_label(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# 23andMe file using GRCh38 coordinates\nrs1\t1\t100\tAG\n",
        )
        meta = parser.get_metadata(f)
        assert meta["build"] == "GRCh38"

    def test_defaults_to_grch37(self, parser: TwentyThreeAndMeParser, tmp_path: Path) -> None:
        f = _write(
            tmp_path,
            "# 23andMe\nrs1\t1\t100\tAG\n",
        )
        meta = parser.get_metadata(f)
        assert meta["build"] == "GRCh37"

    def test_metadata_has_no_snp_count_field(
        self, parser: TwentyThreeAndMeParser, mock_23andme_path: Path
    ) -> None:
        meta = parser.get_metadata(mock_23andme_path)
        assert "snp_count" not in meta


class TestEdgeCases:
    def test_header_only_file_yields_zero_variants(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\n",
        )
        assert parser.can_parse(f) is True
        assert list(parser.parse(f)) == []

    def test_empty_genotype_is_no_call(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "# 23andMe\nrs1\t1\t100\t\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].is_no_call

    def test_three_char_genotype_is_no_call(
        self, parser: TwentyThreeAndMeParser, tmp_path: Path
    ) -> None:
        f = _write(
            tmp_path,
            "# 23andMe\nrs1\t1\t100\tABC\n",
        )
        variants = list(parser.parse(f))
        assert len(variants) == 1
        assert variants[0].is_no_call


class TestAutoDetection:
    def test_registry_detects_23andme(self, mock_23andme_path: Path) -> None:
        from allelix.parsers import detect_parser

        parser = detect_parser(mock_23andme_path)
        assert parser.name == "23andme"

    def test_registry_lookup_by_name(self) -> None:
        from allelix.parsers import get_parser_by_name

        parser = get_parser_by_name("23andme")
        assert isinstance(parser, TwentyThreeAndMeParser)

    def test_mhg_not_confused_with_23andme(self, mock_mhg_path: Path) -> None:
        from allelix.parsers import detect_parser

        parser = detect_parser(mock_mhg_path)
        assert parser.name == "myhappygenes"
